version: '2'

services:

  eureka:
    build: ./eureka
    networks:
      - stock-network
    restart: always
    ports:
       - "7899:7899"
    expose:
       - "7899"
  mysqldb:
    build: ./mysql
    networks:
      - stock-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stock
    ports:
       - "3307:3306"
    restart: always
    expose:
       - "3307"
  uploadexcel:
    build: ./uploadExcel
    networks:
      - stock-network
    restart: always
    ports:
       - "7895:7895"
    expose:
       - "7895"
    depends_on:
      - mysqldb
      - eureka
  infrasecurity:
    build: ./infraSecurity
    networks:
      - stock-network
    restart: always
    ports:
       - "7896:7896"
    expose:
       - "7896"
    depends_on:
      - mysqldb
      - eureka
  company:
    build: ./company
    networks:
      - stock-network
    restart: always
    ports:
       - "7897:7897"
    expose:
       - "7897"
    depends_on:
      - mysqldb
      - eureka
  stockexchange:
    build: ./stockExchange
    networks:
      - stock-network
    restart: always
    ports:
       - "7898:7898"
    expose:
       - "7898"
    depends_on:
      - mysqldb
      - eureka
  zuul:
    build: ./zuul
    networks:
      - stock-network
    restart: always
    ports:
       - "7901:7901"
    expose:
       - "7901"
    depends_on:
      - eureka
  angular:
    build: ./UI
    networks:
      - stock-network
    ports:
       - "7894:7894"
    expose:
       - "7894"
    links: 
      - uploadexcel
      - infrasecurity
      - company
      - stockexchange
      
networks:
  stock-network:
    driver: bridge